### ISSUE TITLE
Deploying chaincodes using API (or SDK)

### ISSUE THREAD

**Issue by nkaramolegos** [hyperledger-bevel/bevel-operator-fabric#22]
Can I deploy the chaincode using API? As I can see in order to install the chaincode I have to use kubectl hlf chaincode install. Can I do that from my code using an API?

**Comment by Dviejopomata** [comment]
Hi @nkaramolegos 

The command `kubectl hlf chaincode install` is for testing purposes, you can use it in your CI/CD pipeline.

On the other hand, if you want to build an API you will need to use a programming language, preferably Golang.

You can see how the chaincode is being installed right now by looking at this code:

https://github.com/kfsoftware/hlf-operator/blob/main/kubectl-hlf/cmd/chaincode/install.go

**Comment by nkaramolegos** [comment]
So the API is not built in this repository. I have to build the API and each time I get a request to install the chaincode I have to call something like the part of the code in install.go file?

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 

No, it's not built in this repository, the goal of this project is to deploy components in Kubernetes, not provide management functionalities, the kubectl plugin is just to get started.
